default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_analytics_development
  host: localhost
  socket: /tmp/.s.PGSQL.5432

test:
  <<: *default
  database: search_analytics_test
  host: localhost
  socket: /tmp/.s.PGSQL.5432

production:
  <<: *default
  database: search_analytics_production
  username: search_analytics
  password: <%= ENV["SEARCH_ANALYTICS_DATABASE_PASSWORD"] %>
  host: localhost
  socket: /tmp/.s.PGSQL.5432
